apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: guestbook-app
    spec:
      containers:
          - name: redis
            image: redis
            ports:
              - containerPort: 6379